version: '3.7'
services:
  dev:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      PORT: 5000
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    command: sleep infinity
    volumes:
      - type: bind
        source: .
        target: /project
